### PR TITLE
Update tracking-carrier-values

### PR DESCRIPTION
**Pull request by traci707**
# [DEVDOCS-2977](https://jira.bigcommerce.com/browse/DEVDOCS-2977)

## What changed?
Removed Royalmail from the tracking-carrier list

### CODE REVIEW

**Review by markcmurphy — APPROVED** [review]

**Review by uwikaiddi — APPROVED** [review]

**Comment by ed-parry** [comment]
Hi there, is there a replacement value/service that should be used instead of Royal Mail, or is it no longer supported at all?

**Comment by traci707** [comment]
Roger Qian said the following: 
If they’re using control panel UI then Royal Mail should be available in the Create Shipment modals.

If they’re using API then they can provide a value of royalmail in the shipping_provider field i.e. https://developer.bigcommerce.com/api-reference/store-management/orders/order-shipments/createordershipments

**Comment by ed-parry** [comment]
Thanks, @traci707. I understand with the UI, but though the API from what I can see this PR removes that exact value from the documentation, which I presume was done because it was removed from the system itself? It just looks like the whole record being removed here suggests the API would no longer accept it?

**Comment by bc-rogq** [comment]
> Thanks, @traci707. I understand with the UI, but though the API from what I can see this PR removes that exact value from the documentation, which I presume was done because it was removed from the system itself? It just looks like the whole record being removed here suggests the API would no longer accept it?

@ed-parry, sharing some additional context, currently we support shipment tracking links via native tracking carriers and AfterShip tracking carriers. 

Historically, it was possible to create Royal Mail shipment tracking links via both methods. Developers could provide a value of **royalmail** in the **shipping_provider** field (which generates a tracking link that redirects users to the Royal Mail tracking website) OR provide **royal-mail** in the **tracking_carrier** field (which redirects users to the AfterShip tracking website).

However, as captured by [SHIPPING-1134](https://jira.bigcommerce.com/browse/SHIPPING-1134) AfterShip removed support for Royal Mail at the end of 2017 (all Royal Mail tracking links created with AfterShip since 2017 have redirected users to a AfterShip website with no tracking information displayed), as such we have updated our API functionality to no longer accept the **royal-mail** value in the **tracking_carrier** field. Developers can still provider a value of **royalmail** in the **shipping_provider** field to create shipment tracking links which we have documented [here](https://developer.bigcommerce.com/api-reference/store-management/orders/order-shipments/createordershipments).

**Comment by ed-parry** [comment]
Thank you @bc-rogq, that clears up my confusion. Appreciate the responses from the team here!

**Pull request merged**
