### PR TITLE
Devdocs-2803 - Developer guide to using the API to creating channel specific customers

### PR DESCRIPTION
**Pull request by markcmurphy**
# [DEVDOCS-2803](https://jira.bigcommerce.com/browse/DEVDOCS-2803)

### CODE REVIEW

**Review by valentindellangela — DISMISSED** [review]
👏  Great write up! I think it's very clear / easy to understand.

**Review by mjhmatt — DISMISSED** [review]
This is awesome, perfectly articulated!

**Review by traci707 — CHANGES_REQUESTED** [review]
Mark, I added editorial suggestions, feel free to take those that you are comfortable with.  I noticed the following:
- Both `channel_id` and `channel_ids` were used. I suggested changing them all to `channel_id`.
- Both channel-specific and channel specific were used. I suggested changing them all to channel-specific.
- I noticed there were line item number 1 but no 2, so I made those bullet points.
- For the image, we usually reference them from the devdocs\assets\images folder

**Comment by markcmurphy** [comment]
> Mark, I added editorial suggestions, feel free to take those that you are comfortable with. I noticed the following:
> 
> * Both `channel_id` and `channel_ids` were used. I suggested changing them all to `channel_id`.
> * Both channel-specific and channel specific were used. I suggested changing them all to channel-specific.
> * I noticed there were line item number 1 but no 2, so I made those bullet points.
> * For the image, we usually reference them from the devdocs\assets\images folder

Thanks for the review, @traci707

- I left `channel_id` and `channel_ids` as they were (except a couple of fixes where I mixed them up). Customers have `channel_ids` (`null` or an array of one or more channel IDs) and channels have a `channel_id`.
- Changed to channel-specific
- Removed a lot of both the numbers and bullet points because you're right, they're unnecessary if only one or two steps.
- By using the Google cloud storage, we can get a stable public URL prior to merging the images with the Github Repos. This removes a step from the process where, in order to have working images, you either have to merge them with `main` before your PR or update the image links after since the branch is deleted after PR merge.

**Review by traci707 — APPROVED** [review]

**Pull request merged**
