### PR TITLE
DEVDOCS-4118 [maint.] Update stock changes to manual edit orders

### PR DESCRIPTION
**Pull request by bc-tgomez**
# [DEVDOCS-4118]

## What changed?
* Add note that identifies known stock change behaviors when `awaiting fulfillment` orders are edited manually and 
* Linked to KB article for more info
* Apply MD styleguide to docs

## Anything else?
Related PRs, salient notes, etc

[DEVDOCS-4118]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by WillemHoman — DISMISSED** [review]
Thanks @bc-tgomez

**Review by bc-traciporter — APPROVED** [review]
LGTM

**Review by markcmurphy — COMMENTED** [review]
@bc-tgomez Looks like there are a couple of new directories included here, do you know if that is intentional?

**Comment by bc-tgomez** [comment]
> @bc-tgomez Looks like there are a couple of new directories included here, do you know if that is intentional?

Def not intentional here, @markcmurphy. It was just some MD style clean up and a definition clean up here as well. Good eye. Not sure how directories made it into the branch.

**Pull request merged**
