### PR TITLE
Devdocs 3532 html code tags

### PR DESCRIPTION
**Pull request by bc-andreadao**
# [DEVDOCS-3532](https://jira.bigcommerce.com/browse/DEVDOCS-3532)

##Background:
To fix issues with code blocks, prior PRs/tickets removed HTML Code Tags and replaced them with backticks.

##What this pull request does: 
Fixes markdown issues that still remained (e.g. resulted from using backticks, other issues on the same line)

1. Words Don't Show

2. Less Than and Greater Than Signs

### CODE REVIEW

**Comment by bc-andreadao** [comment]
Not sure if "<theme-name>" is supposed to be showing as a placeholder? (I assumed this for my edits)

**Review by traci707 — COMMENTED** [review]
I found a couple of other changes.

**Comment by slsriehl** [comment]
added more callout / spacing / indentation / code block changes I found. @bc-andreadao can you review my commits on this?

**Comment by bc-andreadao** [comment]
@slsriehl I have reviewed your commits and they are good to go

**Review by slsriehl — APPROVED** [review]
we came, we saw, we changed.

**Review by slsriehl — APPROVED** [review]
once more with feeling -- following branch update with current master.

**Pull request merged**
