### PR TITLE
chore(platform): DEVDOCS-2006 Update Gift Certificate API

### PR DESCRIPTION
**Pull request by serroba**
* Update the V2 Gift Certificate API to explain we can create gift certificates using a transactional currency
* Add a .gitignore file to the project

# [DEVDOCS-2006](https://jira.bigcommerce.com/browse/DEVDOCS-2006)

## What changed?
* Adding currency code to the `POST /api/v2/gift_certificates` endpoint
* Adding a `.gitignore` file

### CODE REVIEW

**Comment by serroba** [comment]
CC @aglensmith

**Comment by aglensmith** [comment]
Sebastian Machuca you are a gentleman and scholar. Thank you!

**Comment by aglensmith** [comment]
@uwikaiddi -- how would you like to handle this?

**Comment by uwikaiddi** [comment]
@aglensmith, have you already made these changes in Stoplight, or are you asking if you can do that?

**Comment by aglensmith** [comment]
@uwikaiddi -- I have not.

**Comment by uwikaiddi** [comment]
@aglensmith, please do so. I'll merge these changes.

**Pull request merged**
