### PR TITLE
Clarify deprecation status of layout file and new API to use

### PR DESCRIPTION
**Pull request by bookernath**
# [STRF-8550](https://jira.bigcommerce.com/browse/STRF-8550)

## What changed?
* Clarify that layout_file is deprecated, and a new API should be used instead. This should be merged after V3 Custom Templates API is documented.

### CODE REVIEW

**Review by aglensmith — DISMISSED** [review]

**Comment by uwikaiddi** [comment]
@bookernath, are you ready for this merge? Asking because it's still in Draft mode.

**Comment by bookernath** [comment]
We don't have the new V3 API publicly documented yet, so I'm going to keep it as a draft for now.

**Comment by uwikaiddi** [comment]
FYI @aglensmith

**Comment by uwikaiddi** [comment]
@bookernath, is this good to merge?

**Comment by bookernath** [comment]
@uwikaiddi this is good to go.

**Review by uwikaiddi — APPROVED** [review]

**Pull request merged**
